Repository codesensegroup/code-study, pull requests merged in 2022-05, with the labels that each got.

#2 feat: 新增AppSubtitle、版本號更新
  .github/workflows/ci-cd.yml
  .github/workflows/ci.yml
  components/app/AppSubtitle.vue
  nuxt.config.js
  package-lock.json
  package.json
  patches/@nuxt+content-theme-docs+0.11.1.patch
Labels: enhancement

#4 fix: fix busuanzi page view issue.
  nuxt.config.js
Labels: bug

#5 feat: 🎸 整合第七章文章
  content/zh/cicd-2.0/chapter7.md
  content/zh/cicd-2.0/chapter7_5.md
Labels: documentation

#7 feat: add authors(contributions) to subtitle
  components/app/AppGithubLink.vue
  components/app/AppSubtitle.vue
  content/zh/cicd-2.0/chapter5.md
  content/zh/index.md
Labels: enhancement

#9 feat: 新增WebApi的第五章節
  content/zh/web-api/chapter5.md
  package-lock.json
Labels: documentation

#14 chore: fix ci-cd, limit master branch
  .github/workflows/ci-cd.yml
Labels: enhancement
